version: '3'
services:
  
  openvas:
      restart: always
      image: irawanhd/openvas:9
      container_name: openvas
      hostname: openvas
      ports:
        - "443:443"
      volumes:
        - "openvasdb:/var/lib/openvas/mgr/"
      environment:
        # CHANGE THIS !
        OV_PASSWORD: admin
        OV_UPDATE: "yes"
      labels:
         deck-chores.dump.command: sh -c "greenbone-nvt-sync; openvasmd --rebuild --progress"
         deck-chores.dump.interval: daily
  # Daily updates to openvas
  cron:
      restart: always
      image: funkyfuture/deck-chores
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  openvasdb:
